### ISSUE TITLE
Handshakes implementation

### ISSUE THREAD

**Issue by TobiKaestle** [Viva-con-Agua/wp-drops-plugin#3]
Implementation of the three different handshakes:

1. No Session exists (redirect to drops)

2. Drops Session-ID exists, but no internal allocation possible

3. Session allocation possible

**Comment by johannsell** [comment]
For the handshake implementation, considering no Session ID exists:

(1) Redirect to Drops Login
`<drops_base_url>/auth/signin/:clientId/:temporaryId`
Now, the user can sign in and Drops Redirects back to Pool using a predefined URL (with temporaryId param).

(2) Request Authorization-Code
Redirect to: `<drops_base_url>/oauth2/code/get/:clientId/:temporaryId`
(Notice: Currently, this URL won't work since Drops need an update)
Now, Drops generates an authorization code and redirects back to Pool using a second predefined URL (with temporaryId param).

(3) Request Access Token
Receiving an authorization code, Pool can query an Access Token using Drops REST API
`<drops_base_url>/oauth2/access_token` considering the following query params:

* `grant_type=authorization_code`
* `client_id=<client_id>`
* `code=<received_code>`
* `redirect_uri=<redirectUri>`

Response:
```
{
    "token_type" : "some_string",
    "access_token" : "a random string",
    "expires_in" : a long,
    "refresh_token" : "a random string"
}
```

(4) Using the received Access Token Pool can request the users profile, by requesting another webservice supplied by the Drops service:

* endpoint: `<drops_base_url>/oauth2/rest/profile`
* query string: `access_token=<access_token>`
